apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: pure-dind
spec:
  serviceAccountName: jenkins
  containers:
  - name: dind
    image: docker:24.0-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    args:
    - --insecure-registry=767225687948.dkr.ecr.us-west-2.amazonaws.com
    - --host=tcp://0.0.0.0:2375
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    - name: docker-lib
      mountPath: /var/lib/docker
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
  volumes:
  - name: workspace
    emptyDir: {}
  - name: docker-lib
    emptyDir: {}
