apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  serviceAccountName: jenkins
  containers:
  
  # Main Jenkins agent
  - name: jnlp
    image: jenkins/inbound-agent:latest
    env:
    - name: CONTAINER_ENV_VAR
      value: jnlp
    volumeMounts:
    - name: workspace
      mountPath: /home/jenkins/agent
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  
  # Kaniko for building Docker images
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: workspace
      mountPath: /home/jenkins/agent
    - name: kaniko-secret
      mountPath: /kaniko/.docker
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
  
  # kubectl for deployments
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - name: workspace
      mountPath: /home/jenkins/agent
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  
  # AWS CLI for ECR
  - name: aws-cli
    image: amazon/aws-cli:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - name: workspace
      mountPath: /home/jenkins/agent
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  
  volumes:
  - name: workspace
    emptyDir: {}
  - name: kaniko-secret
    secret:
      secretName: ecr-credentials
      items:
      - key: .dockerconfigjson
        path: config.json
