apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: custom-agent
spec:
  serviceAccountName: jenkins
  containers:
  - name: jnlp
    image: devopswithjunaid/jenkins-agent-with-tools:latest
    env:
    - name: JENKINS_AGENT_WORKDIR
      value: /home/jenkins/agent
    - name: DOCKER_HOST
      value: unix:///var/run/docker.sock
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
    - name: docker-sock
      mountPath: /var/run/docker.sock
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
  
  volumes:
  - name: workspace-volume
    emptyDir: {}
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: Socket
