apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jenkins-agent
    image: devopswithjunaid/jenkins-agent-dind:latest
    command:
    - sleep
    args:
    - 99d
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2376
    - name: DOCKER_TLS_CERTDIR
      value: /certs
    - name: DOCKER_TLS_VERIFY
      value: "1"
    - name: DOCKER_CERT_PATH
      value: /certs/client
    volumeMounts:
    - name: docker-certs
      mountPath: /certs/client
      readOnly: true
  - name: docker
    image: docker:dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: /certs
    volumeMounts:
    - name: docker-certs
      mountPath: /certs/client
  volumes:
  - name: docker-certs
    emptyDir: {}
