apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: dind-agent
spec:
  serviceAccountName: jenkins
  namespace: jenkins
  securityContext:
    fsGroup: 1000
  initContainers:
    - name: volume-permissions
      image: busybox
      command: 
        - sh
        - -c
        - |
          mkdir -p /home/jenkins/agent /var/lib/docker &&
          chown -R 1000:1000 /home/jenkins/agent /var/lib/docker &&
          chmod -R 777 /home/jenkins/agent /var/lib/docker
      securityContext:
        runAsUser: 0
        privileged: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: docker-lib
          mountPath: /var/lib/docker
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      env:
        - name: JENKINS_AGENT_WORKDIR
          value: /home/jenkins/agent
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

    - name: dind
      image: docker:24.0-dind
      securityContext:
        privileged: true
        runAsUser: 0
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      args:
        - --insecure-registry=767225687948.dkr.ecr.us-west-2.amazonaws.com
        - --host=tcp://0.0.0.0:2375
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: docker-lib
          mountPath: /var/lib/docker
        - name: docker-sock
          mountPath: /var/run

  volumes:
    - name: workspace-volume
      emptyDir: {}
    - name: docker-lib
      emptyDir: {}
    - name: docker-sock
      emptyDir: {}
